language: node_js
node_js: "7"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Tests
      script: npm test
      after_script: npm run coverage
    - stage: Release
      script: "npm run build && npm pack"
      deploy:
        - provider: releases
          file: "cloudkicker-${TRAVIS_TAG}.tgz"
          api_key: "${GITHUB_OAUTH_TOKEN}"
          skip_cleanup: true
          on:
            branch: master
            tags: true
    - stage: Release
      script: npm run build
      deploy:
        - provider: npm
          api_key: "${NPM_API_KEY}"
          skip_cleanup: true
          on:
            branch: master
            tags: true
