language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Tests
      node_js: "7"
      script: npm test
      after_script: npm run coverage
    - stage: Release
      node_js: "7"
      script: npm pack
      deploy:
        - provider: releases
          file: "cloudkicker-*.tgz"
          api_key:
            secure: $GITHUB_OAUTH_TOKEN
          skip_cleanup: true
          on:
            branch: master
            tags: true
    - stage: Release
      node_js: "7"
      script: npm run build
      deploy:
        - provider: npm
          api_key:
            secure: $NPM_API_KEY
          skip_cleanup: true
          on:
            branch: master
            tags: true
